// File generated by flutterfire_cli.
// For all intents and purposes, treat this file as part of your Flutter app configuration.
// This file is never manually edited. Always use FlutterFire CLI to update.
// To regenerate this file, run: flutterfire configure

import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: 'AIzaSyDemoKeyAndroidPlatform123456789',
      appId: '1:123456789012:android:abcdef1234567890abcdef',
      messagingSenderId: '123456789012',
      projectId: 's81-0126-flutter-taskpilot',
      databaseURL: 'https://s81-0126-flutter-taskpilot.firebaseio.com',
      storageBucket: 's81-0126-flutter-taskpilot.appspot.com',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: 'AIzaSyDemoKeyIOSPlatform123456789',
      appId: '1:123456789012:ios:abcdef1234567890abcdef',
      messagingSenderId: '123456789012',
      projectId: 's81-0126-flutter-taskpilot',
      databaseURL: 'https://s81-0126-flutter-taskpilot.firebaseio.com',
      storageBucket: 's81-0126-flutter-taskpilot.appspot.com',
      iosClientId: '123456789012-ios1234567890abcdef.apps.googleusercontent.com',
    );
  }

  static FirebaseOptions get macos {
    return FirebaseOptions(
      apiKey: 'AIzaSyDemoKeyMacOSPlatform123456789',
      appId: '1:123456789012:macos:abcdef1234567890abcdef',
      messagingSenderId: '123456789012',
      projectId: 's81-0126-flutter-taskpilot',
      databaseURL: 'https://s81-0126-flutter-taskpilot.firebaseio.com',
      storageBucket: 's81-0126-flutter-taskpilot.appspot.com',
    );
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: 'AIzaSyDemoKeyWebPlatform123456789',
      appId: '1:123456789012:web:abcdef1234567890abcdef',
      messagingSenderId: '123456789012',
      projectId: 's81-0126-flutter-taskpilot',
      authDomain: 's81-0126-flutter-taskpilot.firebaseapp.com',
      databaseURL: 'https://s81-0126-flutter-taskpilot.firebaseio.com',
      storageBucket: 's81-0126-flutter-taskpilot.appspot.com',
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey: 'AIzaSyDemoKeyWindowsPlatform123456789',
      appId: '1:123456789012:windows:abcdef1234567890abcdef',
      messagingSenderId: '123456789012',
      projectId: 's81-0126-flutter-taskpilot',
      authDomain: 's81-0126-flutter-taskpilot.firebaseapp.com',
      databaseURL: 'https://s81-0126-flutter-taskpilot.firebaseio.com',
      storageBucket: 's81-0126-flutter-taskpilot.appspot.com',
    );
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
